CREATE DATABASE JUMP1;
CREATE TABLE ESTUDIANTES1
(
    ID VARCHAR (100),
    NOMBRE VARCHAR (100),
    EDAD VARCHAR(10),
    PAIS VARCHAR (100)
);

ALTER TABLE ESTUDIANTES1
ADD EDAD VARCHAR (10);

SELECT
PAIS
FROM ESTUDIANTES1;

DROP TABLE ESTUDIANTES1;